trigger:
  branches:
    include:
      - Develop5
  paths:
    include:
      - frontend/**

pool:
  vmImage: 'windows-latest'

variables:
  frontendFolder: 'frontend/PeopleTrackerFrontEnd'

stages:
- stage: Build
  jobs:
  - job: BuildReact
    displayName: 'Build React Frontend'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js 18'

    - script: |
        cd $(frontendFolder)
        npm ci
        npm run build
        dir dist
      displayName: 'Install dependencies and build React app'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/frontend/PeopleTrackerFrontEnd/dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
      displayName: 'Copy build output'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
        ArtifactName: 'frontend'
      displayName: 'Publish frontend artifact'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployFrontend
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: frontend

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'PeopleTrackerServiceConnectionToDeploy'
              appType: 'webApp'
              appName: 'peopletrackerfrontend'
              package: '$(Pipeline.Workspace)/frontend'
            displayName: 'Deploy frontend to Azure App Service'
